spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:${USER_DB_PORT:5432}/user_db?TimeZone=Asia/Ho_Chi_Minh
    username: postgres
    password: ${DB_PASSWORD:Haibabon@234}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/master.xml
    enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

server:
  port: 8082

kafka:
  topic:
    create-user: create-user-command-topic

# ===== EUREKA =====
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# ===== INTERNAL SERVICE SECRET =====
internal:
  secret: ${INTERNAL_SECRET:change-me-in-prod}

# ===== LOGGING =====
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
